version: '3.3'
services:

  netspeed-db:
    image: mysql:8.0
    container_name: netspeed-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql

  netspeed-scheduler:
    container_name: netspeed-scheduler
    image: netspeed
    environment:
      - CONTAINER_ROLE=scheduler
      - APP_ENV=local
    volumes:
      - ./src:/var/www
      - ./.env:/var/www/.env
      - ./start.sh:/usr/local/bin/start
    depends_on:
      - netspeed-db

  netspeed-adminer:
    image: adminer
    container_name: netspeed-adminer
    ports:
      - 28088:8080
    environment:
      - ADMINER_DEFAULT_SERVER=netspeed-db
      - ADMINER_DESIGN=lucas-sandery
    depends_on:
      - netspeed-db

volumes:
  mysql:
    driver: "local"
